version: '3'

services:
  database:
    container_name: zalopay-db
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: merchant