spring:
  application:
    name: payment-engine-service
  datasource:
    # TODO: Set up SSL for other environments
    url: jdbc:postgresql://localhost:5432/merchant
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8082/eureka}
jasypt:
  encryptor:
    password: test